//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWorkstationTests.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalBDEntities : DbContext
    {
        public HospitalBDEntities()
            : base("name=HospitalBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Diagnoses> Diagnoses { get; set; }
        public virtual DbSet<Doctor_s_Appointment> Doctor_s_Appointment { get; set; }
        public virtual DbSet<HospitalDepartments> HospitalDepartments { get; set; }
        public virtual DbSet<HospitalPatients> HospitalPatients { get; set; }
        public virtual DbSet<HospitalPosts> HospitalPosts { get; set; }
        public virtual DbSet<HospitalWards> HospitalWards { get; set; }
        public virtual DbSet<HospitalWorkers> HospitalWorkers { get; set; }
        public virtual DbSet<Parameters> Parameters { get; set; }
        public virtual DbSet<PatientInfo> PatientInfo { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TemperatureSheet> TemperatureSheet { get; set; }
        public virtual DbSet<TimeOfDay> TimeOfDay { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WorkerInWards> WorkerInWards { get; set; }
    }
}
