//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWorkstationTests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalPatients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HospitalPatients()
        {
            this.Doctor_s_Appointment = new HashSet<Doctor_s_Appointment>();
            this.PatientInfo = new HashSet<PatientInfo>();
            this.TemperatureSheet = new HashSet<TemperatureSheet>();
        }
    
        public int IdPatient { get; set; }
        public string NamePatient { get; set; }
        public string SurnamePatient { get; set; }
        public string PatronymicPatient { get; set; }
        public Nullable<int> WardId { get; set; }
        public string RegistrationNumber { get; set; }
        public int IdDiagnosis { get; set; }
        public System.DateTime BirthdayPatient { get; set; }
        public System.DateTime ArrivalDate { get; set; }
    
        public virtual Diagnoses Diagnoses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor_s_Appointment> Doctor_s_Appointment { get; set; }
        public virtual HospitalWards HospitalWards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientInfo> PatientInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemperatureSheet> TemperatureSheet { get; set; }
    }
}
