//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWorkstationTests.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemperatureSheet
    {
        public int IdRecord { get; set; }
        public int PatientId { get; set; }
        public System.DateTime DateStaying { get; set; }
        public int TimeId { get; set; }
        public int ParameterId { get; set; }
        public string Value { get; set; }
    
        public virtual HospitalPatients HospitalPatients { get; set; }
        public virtual Parameters Parameters { get; set; }
        public virtual TimeOfDay TimeOfDay { get; set; }
    }
}
